;!function(){try { var e="undefined"!=typeof globalThis?globalThis:"undefined"!=typeof global?global:"undefined"!=typeof window?window:"undefined"!=typeof self?self:{},n=(new e.Error).stack;n&&((e._debugIds|| (e._debugIds={}))[n]="921f77a5-b71e-2735-344b-3b5d7f318d12")}catch(e){}}();
module.exports = [
"[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/types/fp.js [app-ssr] (ecmascript)", ((__turbopack_context__) => {
"use strict";

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */ __turbopack_context__.s([
    "ERR",
    ()=>ERR,
    "OK",
    ()=>OK,
    "unwrap",
    ()=>unwrap,
    "unwrapAsync",
    ()=>unwrapAsync
]);
function OK(value) {
    return {
        ok: true,
        value
    };
}
function ERR(error) {
    return {
        ok: false,
        error
    };
}
function unwrap(r) {
    if (!r.ok) {
        throw r.error;
    }
    return r.value;
}
async function unwrapAsync(pr) {
    const r = await pr;
    if (!r.ok) {
        throw r.error;
    }
    return r.value;
} //# sourceMappingURL=fp.js.map
}),
"[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/lib/schemas.js [app-ssr] (ecmascript)", ((__turbopack_context__) => {
"use strict";

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */ __turbopack_context__.s([
    "collectExtraKeys",
    ()=>collectExtraKeys,
    "parse",
    ()=>parse,
    "safeParse",
    ()=>safeParse
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$node_modules$2f$zod$2f$v3$2f$ZodError$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/node_modules/zod/v3/ZodError.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$errors$2f$sdkvalidationerror$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/errors/sdkvalidationerror.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$types$2f$fp$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/types/fp.js [app-ssr] (ecmascript)");
;
;
;
function parse(rawValue, fn, errorMessage) {
    try {
        return fn(rawValue);
    } catch (err) {
        if (err instanceof __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$node_modules$2f$zod$2f$v3$2f$ZodError$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["ZodError"]) {
            throw new __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$errors$2f$sdkvalidationerror$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["SDKValidationError"](errorMessage, err, rawValue);
        }
        throw err;
    }
}
function safeParse(rawValue, fn, errorMessage) {
    try {
        return (0, __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$types$2f$fp$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["OK"])(fn(rawValue));
    } catch (err) {
        return (0, __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$types$2f$fp$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["ERR"])(new __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$errors$2f$sdkvalidationerror$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["SDKValidationError"](errorMessage, err, rawValue));
    }
}
function collectExtraKeys(obj, extrasKey, optional) {
    return obj.transform((val)=>{
        const extras = {};
        const { shape } = obj;
        for (const [key] of Object.entries(val)){
            if (key in shape) {
                continue;
            }
            const v = val[key];
            if (typeof v === "undefined") {
                continue;
            }
            extras[key] = v;
            delete val[key];
        }
        if (optional && Object.keys(extras).length === 0) {
            return val;
        }
        return {
            ...val,
            [extrasKey]: extras
        };
    });
} //# sourceMappingURL=schemas.js.map
}),
"[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/lib/primitives.js [app-ssr] (ecmascript)", ((__turbopack_context__) => {
"use strict";

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */ __turbopack_context__.s([
    "abortSignalAny",
    ()=>abortSignalAny,
    "allRequired",
    ()=>allRequired,
    "combineSignals",
    ()=>combineSignals,
    "compactMap",
    ()=>compactMap,
    "invariant",
    ()=>invariant,
    "remap",
    ()=>remap
]);
class InvariantError extends Error {
    constructor(message){
        super(message);
        this.name = "InvariantError";
    }
}
function invariant(condition, message) {
    if (!condition) {
        throw new InvariantError(message);
    }
}
function remap(inp, mappings) {
    let out = {};
    if (!Object.keys(mappings).length) {
        out = inp;
        return out;
    }
    for (const [k, v] of Object.entries(inp)){
        const j = mappings[k];
        if (j === null) {
            continue;
        }
        out[j ?? k] = v;
    }
    return out;
}
function combineSignals(...signals) {
    const filtered = [];
    for (const signal of signals){
        if (signal) {
            filtered.push(signal);
        }
    }
    switch(filtered.length){
        case 0:
        case 1:
            return filtered[0] || null;
        default:
            if ("any" in AbortSignal && typeof AbortSignal.any === "function") {
                return AbortSignal.any(filtered);
            }
            return abortSignalAny(filtered);
    }
}
function abortSignalAny(signals) {
    const controller = new AbortController();
    const result = controller.signal;
    if (!signals.length) {
        return controller.signal;
    }
    if (signals.length === 1) {
        return signals[0] || controller.signal;
    }
    for (const signal of signals){
        if (signal.aborted) {
            return signal;
        }
    }
    function abort() {
        controller.abort(this.reason);
        clean();
    }
    const signalRefs = [];
    function clean() {
        for (const signalRef of signalRefs){
            const signal = signalRef.deref();
            if (signal) {
                signal.removeEventListener("abort", abort);
            }
        }
    }
    for (const signal of signals){
        signalRefs.push(new WeakRef(signal));
        signal.addEventListener("abort", abort);
    }
    return result;
}
function compactMap(values) {
    const out = {};
    for (const [k, v] of Object.entries(values)){
        if (typeof v !== "undefined") {
            out[k] = v;
        }
    }
    return out;
}
function allRequired(v) {
    if (Object.values(v).every((x)=>x == null)) {
        return void 0;
    }
    return v;
} //# sourceMappingURL=primitives.js.map
}),
"[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/webhooks.js [app-ssr] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "WebhookVerificationError",
    ()=>WebhookVerificationError,
    "validateEvent",
    ()=>validateEvent
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f$standardwebhooks$2f$dist$2f$index$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/standardwebhooks/dist/index.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookbenefitcreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookbenefitcreatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookbenefitgrantcreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookbenefitgrantcreatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookbenefitgrantrevokedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookbenefitgrantrevokedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookbenefitgrantupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookbenefitgrantupdatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookbenefitgrantcycledpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookbenefitgrantcycledpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookbenefitupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookbenefitupdatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcheckoutcreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookcheckoutcreatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcheckoutupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookcheckoutupdatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookordercreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookordercreatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookorderrefundedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookorderrefundedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookorderupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookorderupdatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookorderpaidpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookorderpaidpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookorganizationupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookorganizationupdatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookproductcreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookproductcreatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookproductupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookproductupdatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookrefundcreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookrefundcreatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookrefundupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookrefundupdatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhooksubscriptionactivepayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhooksubscriptionactivepayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhooksubscriptioncanceledpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhooksubscriptioncanceledpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhooksubscriptioncreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhooksubscriptioncreatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhooksubscriptionrevokedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhooksubscriptionrevokedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhooksubscriptionuncanceledpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhooksubscriptionuncanceledpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhooksubscriptionupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhooksubscriptionupdatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcustomercreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookcustomercreatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcustomerupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookcustomerupdatedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcustomerdeletedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookcustomerdeletedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcustomerstatechangedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookcustomerstatechangedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcustomerseatassignedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookcustomerseatassignedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcustomerseatclaimedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookcustomerseatclaimedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcustomerseatrevokedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/components/webhookcustomerseatrevokedpayload.js [app-ssr] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$errors$2f$sdkvalidationerror$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Downloads/nodebase-main/node_modules/@polar-sh/sdk/dist/esm/models/errors/sdkvalidationerror.js [app-ssr] (ecmascript)");
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
class WebhookVerificationError extends Error {
    constructor(message){
        super(message);
        this.message = message;
    }
}
const parseEvent = (parsed)=>{
    try {
        switch(parsed.type){
            case "customer.created":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcustomercreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookCustomerCreatedPayload$inboundSchema"].parse(parsed);
            case "customer.updated":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcustomerupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookCustomerUpdatedPayload$inboundSchema"].parse(parsed);
            case "customer.deleted":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcustomerdeletedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookCustomerDeletedPayload$inboundSchema"].parse(parsed);
            case "customer.state_changed":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcustomerstatechangedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookCustomerStateChangedPayload$inboundSchema"].parse(parsed);
            case "customer_seat.assigned":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcustomerseatassignedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookCustomerSeatAssignedPayload$inboundSchema"].parse(parsed);
            case "customer_seat.claimed":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcustomerseatclaimedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookCustomerSeatClaimedPayload$inboundSchema"].parse(parsed);
            case "customer_seat.revoked":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcustomerseatrevokedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookCustomerSeatRevokedPayload$inboundSchema"].parse(parsed);
            case "benefit.created":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookbenefitcreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookBenefitCreatedPayload$inboundSchema"].parse(parsed);
            case "benefit_grant.created":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookbenefitgrantcreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookBenefitGrantCreatedPayload$inboundSchema"].parse(parsed);
            case "benefit_grant.cycled":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookbenefitgrantcycledpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookBenefitGrantCycledPayload$inboundSchema"].parse(parsed);
            case "benefit_grant.revoked":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookbenefitgrantrevokedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookBenefitGrantRevokedPayload$inboundSchema"].parse(parsed);
            case "benefit_grant.updated":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookbenefitgrantupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookBenefitGrantUpdatedPayload$inboundSchema"].parse(parsed);
            case "benefit.updated":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookbenefitupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookBenefitUpdatedPayload$inboundSchema"].parse(parsed);
            case "checkout.created":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcheckoutcreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookCheckoutCreatedPayload$inboundSchema"].parse(parsed);
            case "checkout.updated":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookcheckoutupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookCheckoutUpdatedPayload$inboundSchema"].parse(parsed);
            case "order.created":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookordercreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookOrderCreatedPayload$inboundSchema"].parse(parsed);
            case "order.paid":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookorderpaidpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookOrderPaidPayload$inboundSchema"].parse(parsed);
            case "order.updated":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookorderupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookOrderUpdatedPayload$inboundSchema"].parse(parsed);
            case "order.refunded":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookorderrefundedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookOrderRefundedPayload$inboundSchema"].parse(parsed);
            case "organization.updated":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookorganizationupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookOrganizationUpdatedPayload$inboundSchema"].parse(parsed);
            case "product.created":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookproductcreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookProductCreatedPayload$inboundSchema"].parse(parsed);
            case "product.updated":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookproductupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookProductUpdatedPayload$inboundSchema"].parse(parsed);
            case "refund.created":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookrefundcreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookRefundCreatedPayload$inboundSchema"].parse(parsed);
            case "refund.updated":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhookrefundupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookRefundUpdatedPayload$inboundSchema"].parse(parsed);
            case "subscription.active":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhooksubscriptionactivepayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookSubscriptionActivePayload$inboundSchema"].parse(parsed);
            case "subscription.canceled":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhooksubscriptioncanceledpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookSubscriptionCanceledPayload$inboundSchema"].parse(parsed);
            case "subscription.created":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhooksubscriptioncreatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookSubscriptionCreatedPayload$inboundSchema"].parse(parsed);
            case "subscription.revoked":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhooksubscriptionrevokedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookSubscriptionRevokedPayload$inboundSchema"].parse(parsed);
            case "subscription.uncanceled":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhooksubscriptionuncanceledpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookSubscriptionUncanceledPayload$inboundSchema"].parse(parsed);
            case "subscription.updated":
                return __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$components$2f$webhooksubscriptionupdatedpayload$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookSubscriptionUpdatedPayload$inboundSchema"].parse(parsed);
            default:
                throw new __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$errors$2f$sdkvalidationerror$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["SDKValidationError"](`Unknown event type: ${parsed.type}`, parsed.type, parsed);
        }
    } catch (error) {
        throw new __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f40$polar$2d$sh$2f$sdk$2f$dist$2f$esm$2f$models$2f$errors$2f$sdkvalidationerror$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["SDKValidationError"]("Failed to parse event", error, parsed);
    }
};
const validateEvent = (body, headers, secret)=>{
    const base64Secret = Buffer.from(secret, "utf-8").toString("base64");
    const webhook = new __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f$standardwebhooks$2f$dist$2f$index$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["Webhook"](base64Secret);
    try {
        const parsed = webhook.verify(body, headers);
        return parseEvent(parsed);
    } catch (error) {
        if (error instanceof __TURBOPACK__imported__module__$5b$project$5d2f$Downloads$2f$nodebase$2d$main$2f$node_modules$2f$standardwebhooks$2f$dist$2f$index$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__["WebhookVerificationError"]) {
            throw new WebhookVerificationError(error.message);
        }
        throw error;
    }
};
;
 //# sourceMappingURL=webhooks.js.map
}),
];

//# debugId=921f77a5-b71e-2735-344b-3b5d7f318d12
//# sourceMappingURL=6ec0f_%40polar-sh_sdk_dist_esm_896d4926._.js.map