var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/[...all]/route.js")
R.c("server/chunks/6ec0f_61d7f845._.js")
R.c("server/chunks/[root-of-the-server]__189e54fd._.js")
R.c("server/chunks/6ec0f_next_dist_4e95bda0._.js")
R.c("server/chunks/6ec0f_@opentelemetry_api_build_esm_4d627f76._.js")
R.c("server/chunks/6ec0f_@polar-sh_sdk_dist_esm_models_errors_abf0dbc4._.js")
R.c("server/chunks/6ec0f_@polar-sh_sdk_dist_esm_models_components_metricperiod_d7e8e89e.js")
R.c("server/chunks/6ec0f_@polar-sh_sdk_dist_esm_models_components_metricstotals_7a5d8513.js")
R.c("server/chunks/6ec0f_@polar-sh_sdk_dist_esm_models_components_eb069daa._.js")
R.c("server/chunks/6ec0f_@polar-sh_sdk_dist_esm_models_operations_f1acce6a._.js")
R.c("server/chunks/6ec0f_@polar-sh_sdk_dist_esm_funcs_811eb775._.js")
R.c("server/chunks/6ec0f_@polar-sh_sdk_dist_esm_sdk_8d765ce3._.js")
R.c("server/chunks/6ec0f_@polar-sh_sdk_dist_esm_9aa17f36._.js")
R.c("server/chunks/fa213_zod_v3_89f71d79._.js")
R.c("server/chunks/6ec0f_zod_b9d8cf69._.js")
R.c("server/chunks/6ec0f_@better-auth_core_dist_0f7a2421._.js")
R.c("server/chunks/6ec0f_jose_dist_webapi_daaeff73._.js")
R.c("server/chunks/6ec0f_better-auth_dist_shared_c8571946._.js")
R.c("server/chunks/6ec0f_better-auth_dist_plugins_0b39b4ae._.js")
R.c("server/chunks/6ec0f_better-auth_dist_74ad9966._.js")
R.c("server/chunks/6ec0f_kysely_dist_esm_operation-node_6b9f8bee._.js")
R.c("server/chunks/6ec0f_kysely_dist_esm_query-builder_a7df2438._.js")
R.c("server/chunks/6ec0f_kysely_dist_esm_schema_789d3351._.js")
R.c("server/chunks/6ec0f_kysely_dist_esm_27d370b6._.js")
R.c("server/chunks/6ec0f_95226c38._.js")
R.c("server/chunks/035c4__next-internal_server_app_api_auth_[___all]_route_actions_4090f094.js")
R.m("[project]/Downloads/nodebase-main/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/Downloads/nodebase-main/app/api/auth/[...all]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/Downloads/nodebase-main/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/Downloads/nodebase-main/app/api/auth/[...all]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
