var R=require("./chunks/[turbopack]_runtime.js")("server/instrumentation.js")
R.c("server/chunks/[root-of-the-server]__4c74aa95._.js")
R.c("server/chunks/6ec0f_@sentry_core_build_cjs_70a9767f._.js")
R.c("server/chunks/6ec0f_@opentelemetry_api_build_esm_fd6da124._.js")
R.c("server/chunks/6ec0f_@opentelemetry_f748543d._.js")
R.c("server/chunks/6ec0f_@opentelemetry_semantic-conventions_build_esm_091db6ef._.js")
R.c("server/chunks/6ec0f_2a35f140._.js")
R.c("server/chunks/6ec0f_@sentry_node-core_build_cjs_c5ee5a7b._.js")
R.c("server/chunks/6ec0f_@apm-js-collab_code-transformer_pkg_orchestrion_js_37ca2c17.js")
R.c("server/chunks/6ec0f_@apm-js-collab_code-transformer_index_8aac0f0c.js")
R.c("server/chunks/6ec0f_@sentry_node_build_cjs_e44395e4._.js")
R.c("server/chunks/6ec0f_@sentry_nextjs_build_cjs_067d1cdc._.js")
R.c("server/chunks/6ec0f_2db8062b._.js")
R.c("server/chunks/[root-of-the-server]__f04d85e4._.js")
R.m("[project]/Downloads/nodebase-main/instrumentation.ts [instrumentation] (ecmascript)")
module.exports=R.m("[project]/Downloads/nodebase-main/instrumentation.ts [instrumentation] (ecmascript)").exports
